### ISSUE TITLE
problem in installation - step 8

### ISSUE THREAD

**Issue by ariasamin** [AnantharamanLab/METABOLIC#103]
Hello, 
I got a problem in installation
I have a problem with  "**bash run_to_setup.sh**", it stops in:

Motif/sox_genes/06.test_soxB_motif.pl
Motif/sox_genes/07.find_soxC_motif.pl
**Motif/sox_genes/08.test_soxC_motif.pl**

**### Then I started to install the from .sh file and I got an error in:**

(metabolic) [narges@node1910 METABOLIC]$ **gdown --quiet https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw**
Traceback (most recent call last):
  File "/home/narges/.conda/envs/metabolic/bin/gdown", line 10, in <module>
    sys.exit(main())
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/gdown/cli.py", line 99, in main
    download(
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/gdown/download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/narges/.conda/envs/metabolic/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    **raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?**

Thank you for your time,
- Narges

**Comment by ChaoLab** [comment]
It seems that you have something wrong with using gdown. 
There is an alternative to directly download the test tgz file from "https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw" and decompress it manually. This will be much easier than solving the potential environment set-up issues

**Comment by ariasamin** [comment]
Thank you so much for your reply, 
You are right. The problem was with "gdown".
As I found "gdown" shows different behavior in different linux environment, I installed "gdown" locally and it worked!!

I appreciate your help
- Narges
