### ISSUE TITLE
Installation of

### ISSUE THREAD

**Issue by B-1991-ing** [AnantharamanLab/METABOLIC#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Dear all,

Thank you very much for developing the docker installation for METABOLIC. My current boss likes it very much and suggested me this paper - METABOLIC: High-throughput profiling of microbial genomes for functional traits, biogeochemistry, and community-scale metabolic networks.

I installed the METABOLIC image on my Mac under the terminal directory - /Users/bing/ through the command line - docker pull tin6150/metabolic:4.0.

I then operated the flollowing Build Commands as below after operating the command line - docker pull tin6150/metabolic:4.0.
docker build -t tin6150/base4metabolic  -f Dockerfile.base       .  | tee Dockerfile.base.log
**WHAT I GOT:**
[+] Building 0.1s (1/2)                                                                   
 => [internal] load build definition from Dockerfile.base                            0.0s
 => => transferring dockerfile: 2B                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount033990402/Dockerfile.base: no such file or directory

docker build -t tin6150/perl4metabolic  -f Dockerfile.perl       .  | tee Dockerfile.perl.log
**WHAT I GOT:**
[+] Building 0.1s (1/2)                                                                   
 => [internal] load build definition from Dockerfile.perl                            0.0s
 => => transferring dockerfile: 2B                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount809121847/Dockerfile.perl: no such file or directory

docker build -t tin6150/metabolic       -f Dockerfile.metabolic  .  | tee Dockerfile.log
**WHAT I GOT:**
[+] Building 0.1s (1/2)                                                                   
 => [internal] load build definition from Dockerfile.metabolic                       0.0s
 => => transferring dockerfile: 2B                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount398916690/Dockerfile.metabolic: no such file or directory

docker build -t tin6150/metabolic:4.0   -f Dockerfile.metabolic  .  | tee Dockerfile.log
**WHAT I GOT:**
[+] Building 0.1s (1/2)                                                                   
 => [internal] load build definition from Dockerfile.metabolic                       0.0s
 => => transferring dockerfile: 2B                                                   0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount164655761/Dockerfile.metabolic: no such file or directory

IN ADDITION, under the directory - /Users/bing/METABOLIC, I also run this command line - docker run  -v "$(pwd)":/tmp/home --entrypoint "perl" tin6150/metabolic:4.0 /opt/METABOLIC/METABOLIC-G.pl -t 34 -in-gn /Users/bing/Desktop/amplicon_seqs -o /tmp/home/metabolic_out
**WHAT I GOT:**

(base) bing@Bings-MacBook-Pro METABOLIC % docker run  -v "$(pwd)":/tmp/home --entrypoint "perl" tin6150/metabolic:4.0 /opt/METABOLIC/METABOLIC-G.pl -t 34 -in-gn /Users/bing/Desktop/amplicon_seqs -o /tmp/home/metabolic_out
mkdir: cannot create directory ‘/tmp/home/metabolic_out’: File exists
mkdir: cannot create directory ‘/tmp/home/metabolic_out/intermediate_files’: File exists
ls: cannot access '/Users/bing/Desktop/amplicon_seqs/*.fasta': No such file or directory
[2022-03-06 06:00:49] The Prodigal annotation is running...
[2022-03-06 06:00:49] The Prodigal annotation is finished
ls: cannot access '/Users/bing/Desktop/amplicon_seqs/*.faa': No such file or directory
sh: 1: cannot create /Users/bing/Desktop/amplicon_seqs/faa.total: Directory nonexistent
mv: cannot stat '/Users/bing/Desktop/amplicon_seqs/faa.total': No such file or directory
mkdir: cannot create directory ‘/tmp/home/metabolic_out/intermediate_files/Hmmsearch_Outputs’: File exists
[2022-03-06 06:00:50] The hmmsearch is running with 34 cpu threads...

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading

Error: Failed to open sequence file /Users/bing/Desktop/amplicon_seqs/total.faa for reading..........................................

So, my question is I didn't install the docker successfully I think.

I am looking forward your reply.

Best,

Bing Song

**Comment by ChaoLab** [comment]
Hi Bing,
Thank you very much for your interest in our software. Currently, we are not maintaining the docker installation. Instead, we recommend the conda installation approach: `https://github.com/AnantharamanLab/METABOLIC/wiki/Installation#anaconda-environment ` which is much faster and easier. It works well in both Mac and Linux systems. 

Chao

**Comment by B-1991-ing** [comment]
Dear Chao,

Thank you very much for your quick response.

I run the command line - conda env create -f / /Users/bing/Desktop/METABOLIC/METABOLIC_v4.0_env.yml on my Mac under the directory - /Users/bing.
**WHAT I GOT:**
SpecNotFound: /Users/bing/Desktop/METABOLIC/METABOLIC_v4.0_env.yml was not found on anaconda.org.
You may need to be logged in. Try running:
    anaconda login

I run the command line - conda env create -f conda env create -f https://github.com/AnantharamanLab/METABOLIC/blob/master/METABOLIC_v4.0_env.yml under the directory - /Users/bing.
**WHAT I GOT:**
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 980, in safe_load
        return load(stream, SafeLoader, version)
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/Users/bing/opt/anaconda3/lib/python3.9/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
        raise ScannerError(
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 26, column 67:
         ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ... 
                                             ^ (line: 26)

`$ /Users/bing/opt/anaconda3/bin/conda-env create -f https://github.com/AnantharamanLab/METABOLIC/blob/master/METABOLIC_v4.0_env.yml`
....................................

What happened there?

Best,

Bing

**Comment by ChaoLab** [comment]
Did you download the yml file to your server or Mac?

**Comment by B-1991-ing** [comment]
I think so, as I downloaded https://github.com/AnantharamanLab/METABOLIC/blob/master/METABOLIC_v4.0_env.yml to the directory - /Users/bing/Desktop/METABOLIC on my Mac.

**Comment by patriciatran** [comment]
In your command try using the path to the yml file on your computer:

`conda create -n /Users/bing/Desktop/METABOLIC/METABOLIC_v4.0_env.yml`

**Comment by B-1991-ing** [comment]
Hi Patricia,

Thank you very much for your reply.

I run the command line - conda create -n /Users/bing/Desktop/METABOLIC/METABOLIC_v4.0_env.yml on my Mac terminal.

**WHAT I GOT:**

<img width="1369" alt="Screenshot 2022-03-08 at 19 52 52" src="https://user-images.githubusercontent.com/54441633/157305926-e4884c02-20b4-425d-b9a6-9bdfca7166c8.png">


Best,

Bing

**Comment by patriciatran** [comment]
could you try cd into /Users/bing/Desktop/METABOLIC/ and typing:
`conda env create -f METABOLIC_v4.0_env.yml`
and tell me what you get please?

**Comment by B-1991-ing** [comment]
I changed the directory to /Users/bing/Desktop/METABOLIC/ and run the command line - conda env create -f METABOLIC_v4.0_env.yml.

**WHAT I GOT:**

<img width="1370" alt="Screenshot 2022-03-08 at 20 23 52" src="https://user-images.githubusercontent.com/54441633/157310144-59b19f11-979f-43ea-9fd7-2b7757846b32.png">

I run the command line - conda create -n METABOLIC_v4.0_env.yml. The conda environment is "METABOLIC_v4.0_env.yml" instead of "METABOLIC_v4.0".

**WHAT I GOT:**

<img width="1168" alt="Screenshot 2022-03-08 at 20 25 19" src="https://user-images.githubusercontent.com/54441633/157310362-9684f3b1-fe45-4ee7-a6a8-479266c649ab.png">

**Comment by patriciatran** [comment]
ooooh ok. I think the yml file was made for a Linux install -- do we have a way to make it work on mac @ChaoLab ?

**Comment by B-1991-ing** [comment]
You are right. But, I still downloaded the yml file you uploaded a few minutes ago and run it.

**WHAT I GOT**

<img width="1371" alt="Screenshot 2022-03-08 at 21 14 27" src="https://user-images.githubusercontent.com/54441633/157317774-cb32b2aa-edc6-4bcb-aca0-292c51b9390d.png">

**Comment by GianmarcoCastillo** [comment]
Hello, good evening. I want to install Metabolic using Conda on my HPC running Linux. Could you help me with the installation commands? I've already created an environment with R <4, as indicated by the Metabolic program.
