### ISSUE TITLE
gdown fails in run_to_setup.sh

### ISSUE THREAD

**Issue by skeffington** [AnantharamanLab/METABOLIC#92]
Hi,

I was trying the conda install as described but came unstuck at the step to download the test data:

```
gdown --quiet https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw
```

yields the error:

```
Traceback (most recent call last):
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/bin/gdown", line 10, in <module>
    sys.exit(main())
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/gdown/cli.py", line 99, in main
    download(
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/gdown/download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/lustre/home/as1541/.conda/envs/METABOLIC_v4.0/lib/python3.8/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
```

I also tried 

```
gdown --id '1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw'
```
and
```
 gdown --quiet 'https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw'
```
and
```
 wget --no-check-certificate 'https://drive.google.com/uc?id=1JQJpw_elM4IyGo_BIfioy8XnmqgoN-Iw' -O METABOLIC_test_files.tar.gz
```

None of which worked. The latter only downloaded 2kb.

I've just donwloaded in my webrowser instead, but thought I'd post the error in case it affects otheres.
Thanks!
Alastair

**Comment by ChaoLab** [comment]
Hi Alastair,
It may be due to the version upgrading issue of gdown. I used this command to upgrade it - "pip install --upgrade gdown" (Now it is gdown v4.5.1). Now I am able to download the tgz file.

Meanwhile, I have also updated the yml file by using gdown v4.5.1

**Comment by skeffington** [comment]
Great - thanks!
